services:
  cf-auth:
    image: ghcr.io/w9315273/cf-access-validator:latest
    container_name: cf-auth
    networks:
      net:
        ipv4_address: 172.18.100.2
    environment:
      ADDR: "0.0.0.0:9000"
      TEAM_DOMAIN: “${TEAM_DOMAIN}”
      APP_MAP: "blog=${AUD_BLOG};grafana=${AUD_GRAFANA}"
    restart: always

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.100.0/24
          gateway: 172.18.100.1